### ISSUE TITLE
Bug : Proposal Page rendering one of the proposals weird

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#159]
On Testnet, noticed this weird thing going on with some of the proposals

<img width="1624" alt="Screenshot 2023-04-17 at 12 47 31 PM" src="https://user-images.githubusercontent.com/103976531/232554763-3c745568-622f-448d-9a36-a4d9ae725752.png">

**Comment by salieflewis** [comment]
In the coming PR, I've added the html parser to the `ProposalTitle` component. This has solved the majority of the issue, but there is still an instance where a link sticks out past its container. I don't think this will be a problem moving forward because there shouldn't be this much html in a proposal title moving forward. Think this was just a weird test case.

**Comment by salieflewis** [comment]
Resolved #164
