### ISSUE TITLE
Bug : Proposals - language on voting eligibility changes

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#162]
Not sure what the scenario is here, but : 

1.  when I am logged into the wallet that has a token, the language says "You were not eligible to vote on this proposal".
2. when i am logged into a wallet that doesn't have a token, the language says "You did not vote on this proposal"

IMO, let's consolidate that down to one statement, since its in past tense.  - "You did not participate in voting on this proposal"

If proposal is active and we are able to set different text, I would say the language should be "You are not eligible to vote on this proposal"

 lmk what u think @salieflewis @0xTranqui 

https://user-images.githubusercontent.com/103976531/232561361-774c5ce8-5f8d-490b-9e9c-73dbc18d62b8.mov

**Comment by 0xTranqui** [comment]
so the scenario you are screensharing is NOT an active proposal. it is specifically one where the voting period has finished (either succeeded or defeated), and is ready to be queued. this is why both things are in past tense -- that being said I would be down for consolidating the language (in order to simplify things) to just "you did not vote on this proposal", as opposed to also having the "you were not eligible for this proposal" show up for ppl who didnt have voting power at the time

**Comment by losingmyego** [comment]
Think we're on the same page - I was aware the proposal was in the past - however the language changing was the focus of the comment. Totally down for "you did not vote on this proposal", it's way less wordy

**Comment by losingmyego** [comment]
For active proposals - are we cool with "You are not eligible to vote" ?
